import { useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { AnimatePresence, motion, useMotionValueEvent, useReducedMotion, useScroll, useTransform } from 'framer-motion'
import { ArrowDown, ArrowUpRight, Check, ChevronDown, Code2, Globe, GraduationCap, Layers, Smartphone } from 'lucide-react'
import { useCopy } from './language'
import { ProductVisual } from './ProductVisual'
import type { ProductKind } from './ProductVisual'
import './premium.css'

const ease = [.22, 1, .36, 1] as const
const photo = 'https://images.unsplash.com/photo-1753613648242-6b6c5b88e4d1?auto=format&fit=crop&w=1400&q=85'

function InView({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  const reduced = useReducedMotion()
  return <motion.div className={className} initial={{ opacity: 0, y: reduced ? 0 : 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .85, ease }}>{children}</motion.div>
}

export default function PremiumHome() {
  const t = useCopy()
  const reduced = useReducedMotion()
  const [selected, setSelected] = useState<ProductKind>('student')
  const showcase = useRef<HTMLDivElement>(null)
  const { scrollYProgress } = useScroll({ target: showcase, offset: ['start end', 'end start'] })
  const lift = useTransform(scrollYProgress, [0, .4, 1], [65, 0, -35])
  const tilt = useTransform(scrollYProgress, [0, .45, 1], [9, 0, -3])
  const services = [
    { id: 'student' as const, to: '/services#students', icon: GraduationCap, label: t('College projects', 'கல்லூரித் திட்டங்கள்'), caption: t('YOUR IDEA. YOUR UNDERSTANDING. YOUR PROJECT.', 'உங்கள் யோசனை. உங்கள் புரிதல். உங்கள் திட்டம்.'), title: t('Don’t just submit it.\nOwn it.', 'சமர்ப்பிப்பதோடு நிற்காமல்.\nபுரிந்துகொள்ளுங்கள்.'), copy: t('Build a project you’re proud to put your name on. From the first idea to the final demo, we help you understand what you’re creating.', 'உங்கள் பெயரைப் பெருமையாகச் சொல்லும் திட்டத்தை உருவாக்குங்கள். முதல் யோசனையிலிருந்து இறுதிச் செயல்விளக்கம் வரை புரிந்துகொண்டு உருவாக்க உதவுகிறோம்.') },
    { id: 'business' as const, to: '/services#business', icon: Globe, label: t('Business websites', 'வணிக இணையதளங்கள்'), caption: t('FIRST IMPRESSIONS. LASTING POSSIBILITIES.', 'சிறந்த அறிமுகம். நீடித்த வாய்ப்புகள்.'), title: t('Look the part.\nGrow the business.', 'சிறந்த தோற்றம்.\nவளரும் வணிகம்.'), copy: t('Give your business a digital home that feels unmistakably yours. Clear, considered, and made for the people you want to reach.', 'உங்கள் வணிகத்திற்கே உரிய டிஜிட்டல் அடையாளம். உங்கள் வாடிக்கையாளர்களுக்காகத் தெளிவாகவும் நேர்த்தியாகவும் உருவாக்கப்பட்டது.') },
    { id: 'app' as const, to: '/services#apps', icon: Smartphone, label: t('Web & mobile apps', 'வெப் & மொபைல் செயலிகள்'), caption: t('THAT “WHAT IF” DESERVES A CHANCE.', 'உங்கள் புதிய யோசனைக்கு ஒரு வாய்ப்பு.'), title: t('From a little “what if”\nto their everyday.', 'ஒரு சிறிய யோசனையிலிருந்து\nஅன்றாடப் பயன்பாடு வரை.'), copy: t('Your original idea, shaped into an experience people can use. Thoughtful web and mobile apps, built around a real problem.', 'மக்கள் பயன்படுத்தக்கூடிய அனுபவமாக உங்கள் சொந்த யோசனை. உண்மையான பிரச்சினைகளைத் தீர்க்கும் வெப் மற்றும் மொபைல் செயலிகள்.') },
  ]

  return <div className="premium-home">
    <section className="premium-hero">
      <div className="hero-intro container">
        <motion.p className="pill-eyebrow" initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><span className="live-dot" />{t('A new chapter starts with an idea', 'ஒரு யோசனையில் தொடங்கும் புதிய அத்தியாயம்')}<ArrowUpRight size={13} /></motion.p>
        <h1><motion.span initial={{ opacity: 0, y: reduced ? 0 : 45 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .9, ease }}>{t('Think big.', 'பெரிதாகச் சிந்தியுங்கள்.')}</motion.span><motion.span className="hero-accent" initial={{ opacity: 0, y: reduced ? 0 : 45 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 1, delay: .12, ease }}>{t('Build something real.', 'நிஜமாக உருவாக்குங்கள்.')}</motion.span></h1>
        <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: .3 }}><p className="premium-lede">{t('College projects. Business websites. Your next big app.\nA thoughtful technology studio for ideas that deserve to exist.', 'கல்லூரித் திட்டங்கள். வணிக இணையதளங்கள். உங்கள் அடுத்த செயலி.\nஉங்கள் யோசனைகளுக்கு வடிவம் கொடுக்கும் தொழில்நுட்பக் குழு.')}</p><div className="hero-buttons"><Link className="button" to="/contact">{t('Let’s build your idea', 'உங்கள் யோசனையை உருவாக்குவோம்')}<ArrowUpRight size={18} /></Link><a className="hero-secondary" href="#possibilities">{t('Explore the possibilities', 'வாய்ப்புகளை அறியுங்கள்')}<ArrowDown size={16} /></a></div></motion.div>
      </div>
      <div className="showcase-shell container" ref={showcase}>
        <div className="showcase-tabs" role="group" aria-label={t('Choose a preview', 'முன்னோட்டத்தைத் தேர்ந்தெடுங்கள்')}>{services.map(({ id, label, icon: Icon }) => <button key={id} aria-pressed={selected === id} onClick={() => setSelected(id)}><Icon size={16} />{label}{selected === id && <motion.span className="tab-background" layoutId="preview-tab" transition={{ type: 'spring', stiffness: 380, damping: 34 }} />}</button>)}</div>
        <div className="showcase-canvas"><div className="canvas-caption"><span><i />{t('A LITTLE PREVIEW OF WHAT’S POSSIBLE', 'சாத்தியங்களின் ஒரு சிறிய முன்னோட்டம்')}</span><span>ZECQORA — STUDIO / 01</span></div><motion.div className="showcase-product" style={reduced ? {} : { y: lift, rotateX: tilt }}><AnimatePresence mode="wait"><motion.div key={selected} initial={{ opacity: 0, y: reduced ? 0 : 30, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: reduced ? 0 : -15, scale: .98 }} transition={{ duration: .45, ease }}><ProductVisual kind={selected} /></motion.div></AnimatePresence></motion.div><div className="canvas-footer"><span>{t('DESIGNED WITH INTENTION. BUILT WITH YOU.', 'நோக்கத்துடன் வடிவமைத்து. உங்களுடன் உருவாக்கி.')}</span><span className="scroll-cue">{t('Keep exploring', 'மேலும் அறியுங்கள்')}<ArrowDown size={14} /></span></div></div>
      </div>
    </section>

    <div className="expertise-band"><div className="container"><p>{t('SMALL-TOWN ROOTS.\nA WORLD OF POSSIBILITIES.', 'சிற்றூரில் தொடங்கி.\nஎல்லையற்ற வாய்ப்புகளை நோக்கி.')}</p><span><Code2 />{t('Built to work', 'செயல்பட உருவாக்கப்பட்டது')}</span><span><Layers />{t('Designed to matter', 'பயனுள்ள வடிவமைப்பு')}</span><span><GraduationCap />{t('Explained to you', 'உங்களுக்கான விளக்கம்')}</span></div></div>

    <section className="container possibilities" id="possibilities"><InView className="premium-heading"><div><p className="eyebrow">{t('ONE STUDIO. YOUR NEXT BIG THING.', 'ஒரு குழு. உங்கள் அடுத்த பெரிய முயற்சி.')}</p><h2>{t('Different ambitions.\nThe same attention to detail.', 'பல இலக்குகள்.\nஒவ்வொன்றிலும் முழுக் கவனம்.')}</h2></div><p>{t('We bring design, development, and a little extra care to everything we build.', 'வடிவமைப்பு, உருவாக்கம் மற்றும் தனிக் கவனம் — நாங்கள் உருவாக்கும் அனைத்திலும்.')}</p></InView><div className="premium-service-list">{services.map((s, i) => <InView key={s.id} className={`feature-card feature-${s.id}`}><div className="feature-copy"><span className="feature-index">0{i + 1}<span>{s.label}</span></span><p className="eyebrow">{s.caption}</p><h3>{s.title}</h3><p>{s.copy}</p><Link to={s.to} className="round-link">{t('Let’s explore', 'மேலும் அறியுங்கள்')}<span><ArrowUpRight size={21} /></span></Link></div><Link to={s.to} className="feature-art" aria-label={s.label}><ProductVisual kind={s.id} compact /><span className="concept-caption">{t('INTERFACE CONCEPT / ZECQORA', 'இடைமுக மாதிரி / ZECQORA')}</span></Link></InView>)}</div></section>

    <BuildStory />

    <section className="purpose-section"><div className="container"><InView className="purpose-title"><p className="eyebrow">{t('WHY WE’RE HERE', 'எங்கள் நோக்கம்')}</p><h2>{t('Talent has\nno postcode.', 'திறமைக்கு\nஎல்லைகள் இல்லை.')}<span className="purpose-asterisk">✳</span></h2></InView><div className="purpose-grid"><InView className="purpose-photo"><img src={photo} alt={t('A student developing software on a laptop in a library', 'நூலகத்தில் மடிக்கணினியில் மென்பொருள் உருவாக்கும் மாணவர்')} loading="lazy" /><div className="photo-caption">{t('A world of possibility. Wherever you start.', 'எங்கு தொடங்கினாலும். எல்லையற்ற வாய்ப்புகள்.')}<ArrowUpRight size={18} /></div></InView><InView className="purpose-copy"><span className="purpose-coordinate">10.78° N · IDEAS EVERYWHERE</span><h3>{t('Your hometown is\na starting point.\nNever a limit.', 'உங்கள் ஊர்\nஒரு தொடக்கமே.\nஎன்றும் எல்லையல்ல.')}</h3><p>{t('We’re building Zecqora for ambitious students, especially those in rural communities where technical guidance can be hard to find.', 'தொழில்நுட்ப வழிகாட்டுதல் எளிதில் கிடைக்காத கிராமப்புற மாணவர்கள் உட்பட, கனவுகளைக் கொண்ட அனைவருக்காகவும் Zecqora-வை உருவாக்குகிறோம்.')}</p><p>{t('Bring your curiosity. We’ll help you turn it into practical skills, a project you understand, and the confidence to go further.', 'உங்கள் ஆர்வத்தைக் கொண்டு வாருங்கள். அதை நடைமுறைத் திறனாகவும், புரிந்துகொண்ட திட்டமாகவும், முன்னேறும் நம்பிக்கையாகவும் மாற்ற உதவுகிறோம்.')}</p><Link className="round-link" to="/learning">{t('Grow with us', 'எங்களுடன் வளருங்கள்')}<span><ArrowUpRight size={20} /></span></Link></InView></div></div></section>

    <section className="container premium-faq"><InView><p className="eyebrow">{t('A LITTLE CLARITY', 'சில தெளிவான பதில்கள்')}</p><h2>{t('Curious?\nYou’re in good company.', 'கேள்விகள் உள்ளதா?\nகேளுங்கள்.')}</h2><Link to="/contact" className="text-link">{t('Ask us something else', 'வேறு கேள்விகளைக் கேளுங்கள்')}<ArrowUpRight size={16} /></Link></InView><div>{[
      [t('Can I bring my own project idea?', 'என் சொந்த யோசனையுடன் வரலாமா?'),t('Please do. Bring your problem, a rough sketch, or your college brief. We’ll work with you to shape the scope and plan the build.', 'நிச்சயமாக. உங்கள் யோசனை, வரைபடம் அல்லது கல்லூரித் திட்ட விவரங்களுடன் வாருங்கள். ஒன்றாகத் திட்டமிட்டு உருவாக்கலாம்.')],
      [t('Will I understand what we build?', 'நாம் உருவாக்குவது எனக்குப் புரியுமா?'),t('That’s the point. We guide you through the decisions and code, so you can explain your work and present it with confidence.', 'அதுவே நோக்கம். நிரலையும் முடிவுகளையும் விளக்குகிறோம். உங்கள் திட்டத்தை நம்பிக்கையுடன் விளக்கவும் சமர்ப்பிக்கவும் உதவுகிறோம்.')],
      [t('Do you build for businesses too?', 'வணிகங்களுக்கும் சேவை வழங்குகிறீர்களா?'),t('Yes. We design and develop websites, web platforms, and mobile applications around your business needs. Scope, timeline, and pricing are discussed before work begins.', 'ஆம். உங்கள் வணிகத் தேவைக்கேற்ப இணையதளங்கள், வெப் மற்றும் மொபைல் செயலிகளை உருவாக்குகிறோம். பணி, காலக்கெடு மற்றும் விலை முன்பே விவாதிக்கப்படும்.')],
      [t('Can we talk in Tamil?', 'தமிழில் பேசலாமா?'),t('Of course. English or Tamil—choose the language that helps you express your idea best.', 'நிச்சயமாக. உங்கள் யோசனையைச் சிறப்பாகப் பகிர உதவும் தமிழையோ ஆங்கிலத்தையோ தேர்ந்தெடுங்கள்.')],
    ].map(([q,a]) => <details key={q}><summary>{q}<ChevronDown size={18} /></summary><p>{a}</p></details>)}</div></section>

    <section className="closing-section"><div className="closing-orbit" /><InView className="container closing-content"><p className="eyebrow">{t('YOUR NEXT CHAPTER', 'உங்கள் அடுத்த அத்தியாயம்')}</p><h2>{t('Great things start\nwith “what if”.', '“ஏன் கூடாது?” என்பதில்\nதொடங்கும் புதிய முயற்சிகள்.')}</h2><p>{t('You bring the idea. Let’s figure out the rest, together.', 'யோசனையுடன் வாருங்கள். மற்றதை ஒன்றாகக் கண்டறிவோம்.')}</p><Link to="/contact" className="button">{t('Let’s make it happen', 'ஒன்றாக உருவாக்குவோம்')}<ArrowUpRight size={18} /></Link><span className="closing-note"><Check size={13} />{t('English or Tamil. A conversation, not a commitment.', 'தமிழ் அல்லது ஆங்கிலம். முதலில் ஒரு உரையாடல்.')}</span></InView></section>
  </div>
}

function BuildStory() {
  const t = useCopy()
  const target = useRef<HTMLElement>(null)
  const reduced = useReducedMotion()
  const [step, setStep] = useState(0)
  const { scrollYProgress } = useScroll({ target, offset: ['start start', 'end end'] })
  useMotionValueEvent(scrollYProgress, 'change', value => setStep(Math.min(2, Math.floor(value * 3))))
  const steps = [
    { title: t('First, a little curiosity.', 'முதலில், கொஞ்சம் ஆர்வம்.'), copy: t('Every great build begins with a question. Tell us what you’re imagining. We’ll find the starting point together.', 'ஒவ்வொரு உருவாக்கமும் ஒரு கேள்வியில் தொடங்குகிறது. உங்கள் எண்ணத்தைப் பகிருங்கள். ஒன்றாகத் தொடங்கலாம்.'), label: t('THE IDEA', 'யோசனை'), visual: t('What if I\nbuilt it?', 'நானே\nஉருவாக்கினால்?') },
    { title: t('Then, a clear direction.', 'அடுத்து, தெளிவான பாதை.'), copy: t('We connect the dots: the right features, a thoughtful design, and a practical plan. You’re part of every decision.', 'சரியான அம்சங்கள், நேர்த்தியான வடிவமைப்பு மற்றும் நடைமுறைத் திட்டம். ஒவ்வொரு முடிவிலும் உங்கள் பங்கு.'), label: t('THE BUILD', 'உருவாக்கம்'), visual: t('One idea.\nTaking shape.', 'ஒரு யோசனை.\nவடிவம் பெறுகிறது.') },
    { title: t('Finally, something yours.', 'இறுதியில், உங்களுடைய ஒன்று.'), copy: t('A working project. A better website. Your own app. Built with care, explained clearly, and ready for your next chapter.', 'செயல்படும் திட்டம். சிறந்த இணையதளம். உங்கள் சொந்த செயலி. கவனமாக உருவாக்கி, தெளிவாக விளக்கி, அடுத்த கட்டத்திற்குத் தயார்.'), label: t('THE POSSIBILITY', 'புதிய வாய்ப்பு'), visual: t('Look what\nyou built.', 'நீங்கள்\nஉருவாக்கிவிட்டீர்கள்.') },
  ]
  return <section ref={target} className={`build-story ${reduced ? 'story-reduced' : ''}`}><div className="story-sticky container"><div className="story-top"><p className="eyebrow">{t('A LITTLE GUIDANCE. A BIG DIFFERENCE.', 'சிறிய வழிகாட்டுதல். பெரிய மாற்றம்.')}</p><span>{t('SCROLL TO SEE IT TAKE SHAPE', 'உருவாவதைக் காண கீழே நகர்த்துங்கள்')}<ArrowDown size={14} /></span></div><div className="story-layout"><div className="story-copy"><h2>{t('From your first idea.\nTo your next big thing.', 'உங்கள் முதல் யோசனையிலிருந்து.\nஅடுத்த பெரிய முயற்சி வரை.')}</h2><div className="story-steps">{steps.map((s,i) => <div className={`story-step ${step === i ? 'is-active' : ''}`} key={i}><span>0{i+1}</span><div><h3>{s.title}</h3><p>{s.copy}</p></div></div>)}</div></div><div className={`story-visual story-visual-${step}`}><div className="story-visual-meta"><span>{steps[step].label}</span><span>0{step+1} / 03</span></div><AnimatePresence mode="wait"><motion.div key={step} className="story-art" initial={{ opacity: 0, y: reduced ? 0 : 25, rotate: reduced ? 0 : -3 }} animate={{ opacity: 1, y: 0, rotate: 0 }} exit={{ opacity: 0, y: reduced ? 0 : -20 }} transition={{ duration: .4, ease }}>{step === 0 ? <div className="idea-paper"><span>A NOTE TO MY FUTURE SELF</span><h3>{steps[step].visual}</h3><div className="paper-line" /><div className="paper-line short" /><span className="paper-star">✳</span></div> : step === 1 ? <div className="build-blueprint"><span><Code2 size={15} /> YOUR IDEA / IN PROGRESS</span><div className="wire-nav" /><div className="wire-grid"><div /><div /><div /></div><div className="wire-lines"><i /><i /><i /></div><strong>{steps[step].visual}</strong></div> : <div className="finish-card"><span className="finish-check"><Check size={45} strokeWidth={1.4} /></span><h3>{steps[step].visual}</h3><p>{t('Understood. Created. Truly yours.', 'புரிந்துகொண்டு. உருவாக்கி. உங்களுக்கே சொந்தமாக.')}</p><span className="finish-label">YOUR NEXT CHAPTER <ArrowUpRight size={15} /></span></div>}</motion.div></AnimatePresence><div className="story-progress">{steps.map((s,i) => <span className={step >= i ? 'complete' : ''} key={s.label} />)}</div></div></div></div></section>
}
